Repository warmachine028/nike, pull requests merged in 2023-10, with the labels that each got.

#75 [FEATURE 💡] Remove Nike from header in mobile devices
  src/assets/images/index.js
  src/assets/images/nikeLogo.png
  src/components/Navbar.jsx
Labels: enhancement, ✨ goal: improvement, 💻 aspect: code, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted

#79 [DOCS 📄] Page link to icon
  README.md
Labels: documentation, 📄 aspect: text, hacktoberfest, hacktoberfest-accepted

#83 [FIX 🛠️] Navbar is not present in shoe detail page
  src/App.jsx
  src/components/Navbar.jsx
  src/components/ShoeDetails.jsx
  src/constants/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#85 [FEATURE 💡] Change Product Card Design
  src/components/ProductCard.jsx
Labels: ✨ goal: improvement, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted

#91 [FIX 🛠️] Hamburger menu for View Details
  src/App.jsx
  src/components/Button.jsx
  src/components/Navbar.jsx
  src/components/ShoeDetails.jsx
Labels: 🛠 goal: fix, 🕹 aspect: interface, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#97 [FEATURE 💡] Prettier Formatting for consistency
  .eslintrc.cjs
  .husky/.gitignore
  .husky/_/husky.sh
  .husky/pre-commit
  .prettierignore
  .prettierrc
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/Button.jsx
  src/components/Menu.jsx
  src/components/Navbar.jsx
  src/components/ProductCard.jsx
  src/components/Rating.jsx
  src/components/ReviewCard.jsx
  src/components/ServiceCard.jsx
  src/components/ShoeCard.jsx
  src/components/ShoeDetails.jsx
  src/components/ThemeSwitch.jsx
  src/constants/index.js
  src/contexts/MenuContext.tsx
  src/index.css
  src/main.jsx
  src/sections/Cart.jsx
  src/sections/CustomerReviews.jsx
  src/sections/Footer.jsx
  src/sections/Hero.jsx
  src/sections/PopularProducts.jsx
  src/sections/ScrollToTopButton.jsx
  src/sections/Services.jsx
  src/sections/SpecialOffers.jsx
  src/sections/Subscribe.jsx
  src/sections/SuperQuality.jsx
  src/sections/index.jsx
Labels: enhancement, hacktoberfest, feature

#96 [FEATURE 💡] Add Minimalistic Cart UI Design #86
  src/App.jsx
  src/components/Menu.jsx
  src/components/ShoeDetails.jsx
  src/components/ThemeSwitch.jsx
  src/sections/Cart.jsx
  src/sections/index.jsx
Labels: enhancement, hacktoberfest, feature

#102 Fixed Smooth Scrolling
  src/index.css
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#104 [FEATURE 💡] Some UI Improvements
  src/components/ShoeCard.jsx
  src/sections/Hero.jsx
Labels: 🛠 goal: fix, hacktoberfest, 🐞 bug

#109 [FEATURE 💡] dark/light theme improvement
  src/components/Button.jsx
  src/components/Menu.jsx
  src/components/Navbar.jsx
  src/components/ProductCard.jsx
  src/components/ReviewCard.jsx
  src/components/ServiceCard.jsx
  src/components/ShoeDetails.jsx
  src/components/ThemeSwitch.jsx
  src/constants/index.js
  src/index.css
  src/sections/Cart.jsx
  src/sections/CustomerReviews.jsx
  src/sections/Hero.jsx
  src/sections/PopularProducts.jsx
  src/sections/SpecialOffers.jsx
  src/sections/SuperQuality.jsx
  tailwind.config.js
Labels: enhancement, hacktoberfest, feature

#106 [FIX 🛠️] Shift in Page when select option of Navbar
  src/components/Menu.jsx
  src/components/Navbar.jsx
  src/index.css
Labels: 🛠 goal: fix, hacktoberfest, 🐞 bug

#115 [FEATURE 💡] Make Navbar floating
  .husky/_/husky.sh
  helpers/useScroll.js
  src/App.jsx
  src/components/Navbar.jsx
Labels: 🛠 goal: fix, hacktoberfest, 🐞 bug

#117 [FEATURE 💡] Menu needs changes
  src/App.jsx
  src/components/Menu.jsx
Labels: enhancement, hacktoberfest, feature

#118 [Feature]: Added Carousel for Customers
  index.html
  src/assets/images/customer3.jpg
  src/assets/images/customer4.jpg
  src/assets/images/index.js
  src/components/ReviewCard.jsx
  src/constants/index.js
  src/index.css
  src/sections/CustomerReviews.jsx
Labels: enhancement, hacktoberfest, feature

#120 [FIX 🛠️] Scrolling disabled
  src/App.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#126 [FIX 🛠️] Dark mode toggle not working for the first time #125
  src/components/ThemeSwitch.jsx
Labels: 🛠 goal: fix, hacktoberfest, 🐞 bug

#129 fix show cart button
  src/App.jsx
  src/components/Navbar.jsx
  src/components/ThemeSwitch.jsx
Labels: 🛠 goal: fix, hacktoberfest, 🐞 bug

#138 [FEATURE 💡] Update Cart items
  src/components/ProductCard.jsx
  src/sections/Cart.jsx
Labels: enhancement, ⭐ goal: addition, hacktoberfest, feature

#139 [FEATURE 💡] SignIn/SignUp
  src/App.jsx
  src/components/Menu.jsx
  src/sections/Signin.jsx
  src/sections/Signup.jsx
Labels: enhancement, ⭐ goal: addition, hacktoberfest, hacktoberfest-accepted, feature

#141 [FEATURE 💡] Designing of buttons
  src/components/Button.jsx
Labels: enhancement, hacktoberfest, feature

#150 [FIX 🛠️] Add Spacing for "Your Cart" text
  src/sections/Cart.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#144 [FIX 🛠️] Add Spacing for "Your Cart" text
  src/sections/Cart.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#153 [FIX 🛠️] Navbar not working
  src/App.jsx
  src/components/Navbar.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#156 [FIX 🛠️] Outdated Twitter Logo
  src/assets/icons/twitter.svg
Labels: hacktoberfest

#161 [FIX 🛠️] Cart Button looks ugly
  src/components/ProductCard.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#162 [FEATURE 💡] Improve Testimonials
  src/components/ReviewCard.jsx
  src/index.css
  src/sections/CustomerReviews.jsx
Labels: enhancement, ✨ goal: improvement, hacktoberfest, feature

#165 [FEATURE 💡] Element Changing Positions
  src/components/ReviewCard.jsx
Labels: enhancement, hacktoberfest, feature

#166 [FIX 🛠️] Navbar overlaps Cart in Mobile View
  src/sections/Cart.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#176 [FEATURE 💡] Create a Single Product Component and Page #133
  src/App.jsx
  src/components/ProductCard.jsx
  src/components/SingleProduct.jsx
  src/components/SingleProductCard.jsx
  src/constants/index.js
  src/index.css
  src/sections/ProductsPage.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, feature

#178 [FIX 🛠️] Cart Add or Subtract Item
  src/sections/Cart.jsx
Labels: enhancement, 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug

#173 [FEATURE 💡] Animate theme button
  package-lock.json
  package.json
  src/components/ThemeSwitch.jsx
Labels: enhancement, ✨ goal: improvement, hacktoberfest, feature

#183 [FEATURE 💡] Snackbar notifications Added
  package-lock.json
  package.json
  src/App.jsx
  src/components/ProductCard.jsx
Labels: hacktoberfest

#179 [FEATURE 💡] Interactive Cards
  src/components/ReviewCard.jsx
  src/components/ServiceCard.jsx
  src/components/ShoeCard.jsx
  src/sections/Hero.jsx
  src/sections/SpecialOffers.jsx
  src/sections/SuperQuality.jsx
Labels: enhancement, ⭐ goal: addition, hacktoberfest, hacktoberfest-accepted, feature

#185 [FIX 🛠️] Shop now text disappears on hover on light mode
  package-lock.json
  src/components/Button.jsx
Labels: 🛠 goal: fix, hacktoberfest, hacktoberfest-accepted, 🐞 bug
